// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/RyuChk/wire-provider/grpc/provider"
	"github.com/ZecretBone/ips-bff/cmd/bff-grpc/internal/handler"
	"github.com/ZecretBone/ips-bff/cmd/bff-grpc/server"
	"github.com/ZecretBone/ips-bff/internal/config"
	"github.com/ZecretBone/ips-bff/internal/di"
	"github.com/ZecretBone/ips-bff/internal/services/rssi"
	"github.com/google/wire"
)

// Injectors from di.go:

func InitializeContainer() (*Container, func(), error) {
	rssiServiceConfig := config.ProvideRSSIConfig()
	service := rssi.ProvideRSSIService(rssiServiceConfig)
	rssiServiceServer := handler.ProvideBFFServer(service)
	handlers := &handler.Handlers{
		RSSI: rssiServiceServer,
	}
	grpcServerCustomizer := server.ProvideGRPCServerCustomizer(handlers)
	grpcServer, cleanup, err := provider.ProvideGRPCServer(grpcServerCustomizer)
	if err != nil {
		return nil, nil, err
	}
	container := &Container{
		server: grpcServer,
	}
	return container, func() {
		cleanup()
	}, nil
}

// di.go:

var BaseBindingSet = wire.NewSet(di.DatabaseSet, di.ConfigSet, di.ProviderSet)

var MainBindingSet = wire.NewSet(
	ProviderSet,
	BaseBindingSet, provider.WireSet, wire.Struct(new(Container), "*"),
)
