// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_rssiclient is a generated GoMock package.
package mock_rssiclient

import (
	context "context"
	reflect "reflect"

	v1 "github.com/ZecretBone/ips-bff/internal/gen/proto/ips/rssi/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CollectData mocks base method.
func (m *MockService) CollectData(ctx context.Context, body *v1.CollectDataRequest) (*v1.CollectDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectData", ctx, body)
	ret0, _ := ret[0].(*v1.CollectDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectData indicates an expected call of CollectData.
func (mr *MockServiceMockRecorder) CollectData(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectData", reflect.TypeOf((*MockService)(nil).CollectData), ctx, body)
}
